### ISSUE TITLE
Wen eta bypass iso12 iCloud on iPhone XIII

### ISSUE THREAD

**Issue by rnavalgund** [danieldevofficial/umbre0n#1]
Wen ETA @danieldevofficial ???

**Comment by iabem97** [comment]
vry son

**Comment by rnavalgund** [comment]
Ayeee!!
@iabem97 Btw, i got saigon kinda working for Mini2. (right offsets).
Fails at privilege escalation. Possible to hmu on twitter ? would like to speak a bit. (twitter: @ rnavalgund_)
